### ISSUE TITLE
first_flush_volume and second_flush_volume values taken from Prime volume instead of Flushing volumes

### ISSUE THREAD

**Issue by evelyndooley** [SoftFever/OrcaSlicer#4077] opened 2024-02-13 16:12 UTC
### OrcaSlicer Version

1.9.0

### OS version

Windows 11

### Printer

Voron 2.4 with Trad Rack MMU

### How to reproduce

1. Enable Prime tower in process.
2. In any custom G-Code section, utilize placeholder. Example: 
```
G1 E{first_flush_volume}
G1 E{second_flush_volume}
```

### Actual results

For a Prime volume of 15 mm^3:
```
G1 E3.11814
G1 E3.11814
```

### Expected results

For flushing volumes of 70 and 150 for first and second respectively:
```
G1 E14.58...
G1 E31.25...
```

### Project file & Debug log uploads

[Chillet4.zip](https://github.com/SoftFever/OrcaSlicer/files/14269278/Chillet4.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by barsamgr** [comment] 2024-02-17 09:06
You meed to activate "Purge in prime tower" of the printer settings for them to work.

![image](https://github.com/SoftFever/OrcaSlicer/assets/6124340/32273a4c-7e4e-48e3-952f-cb5a1d312dbf)

**Comment by evelyndooley** [comment] 2024-02-17 15:19
Thank you, I missed that setting. It is working as expected now.

**Comment by SoftFever** [comment] 2024-02-29 14:44
Looks like the problem is solved. 
Closing

**Closed by SoftFever** 2024-02-29 14:44 UTC
Labels: bug
