### ISSUE TITLE
Multi color painting only applies to top/bottom shell layers

### ISSUE THREAD

**Issue by cerrunos87** [SoftFever/OrcaSlicer#5152] opened 2024-04-25 17:49 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0

### Operating System (OS)

Windows

### OS Version

Windows 11

### Additional system information

CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 2592 Mhz, 6 Core(s), 12 Logical Processor(s)
Memory: 16GB Physical, 27.8 Virtual
GPU: Nvidia RTX 2060

### Printer

Voron 2.4

### How to reproduce

1. Import Test Object
2. Paint surfaces for different filament colors (Circle, Sphere, and/or Fill)
3. Slice

### Actual results

Object is sliced with filament changes only applied to top and bottom shell layers, not vertical shells.
![mal sliced](https://github.com/SoftFever/OrcaSlicer/assets/155757810/e440c47c-1f94-4687-92e1-a04dc4175370)
![test sliced](https://github.com/SoftFever/OrcaSlicer/assets/155757810/4058e14e-9953-4d76-96a6-11a8111ece93)

### Expected results

Objects should be sliced with surface colors matching painting performed.
![Mal prep](https://github.com/SoftFever/OrcaSlicer/assets/155757810/04820690-8854-491e-89b5-eaa6419b4175)
![test prepare](https://github.com/SoftFever/OrcaSlicer/assets/155757810/a239e4e7-a10c-4514-8cc0-f1e084b5fa26)

### Project file & Debug log uploads

[MMU Malenia bug.zip](https://github.com/SoftFever/OrcaSlicer/files/15118274/MMU.Malenia.bug.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

Edit: Changing shrinkage percentage for all filaments to 100% resolves this issue

**Comment by BioCookieYT** [comment] 2024-04-27 19:14
Experiencing the same behavior, hope a fix is on its way soon

**Comment by Coop25** [comment] 2024-05-13 12:26
I am experiencing something similar as well, it will start off with the correct color and the 2nd to the top layer it will switch to the wrong color, fill in the object and then switch back to the correct color.

3rd layer from top
![image](https://github.com/SoftFever/OrcaSlicer/assets/52174368/29b3f2f7-ff6c-4b93-a23c-0a93e78bdc5e)

2nd layer from top
![image](https://github.com/SoftFever/OrcaSlicer/assets/52174368/e0ed00b7-16e4-4d22-91ed-cee64edca339)

top layer
![image](https://github.com/SoftFever/OrcaSlicer/assets/52174368/76f9df6c-b1df-4c26-987e-ea88f6d9e0ba)

I can also provide my project file if needed

**Comment by raczak** [comment] 2024-06-04 13:23
Hi, same issue here. It's changing filament only on top shell surface since the 2.0.0 OracaSlicer version. On 1.9.X it's working great... Don't know why ...
<img width="826" alt="Capture d’écran 2024-06-04 à 22 21 24" src="https://github.com/SoftFever/OrcaSlicer/assets/9281021/fe1d1bac-d3bc-41ea-9439-649fd538a917">

**Comment by st3venb** [comment] 2024-06-11 23:08
Experiencing the same issue here with 2.1.0-BETA.  Opened up Bambu Studio loaded project file and verified painting works on vertical surfaces there.  This is frustrating to have to use two slicers to achieve my end goal... Subscribed for hopefully a fix later.

**Comment by atl285** [comment] 2024-06-14 20:34
I have the same experience. Color painting is not useable at the moment with Orca Slicer (Version 2.0 & 2.1.0 Beta). I tried to print [this model](https://www.printables.com/de/model/633452-bull-flexi-keychain/files) in 2 colors using the .3mf file.
![multi_color_issue](https://github.com/SoftFever/OrcaSlicer/assets/15815417/363bbd12-d457-4662-8ad6-26acfe6bbf6f)

@SoftFever, did you know it?

**Comment by SuddenlyPineapple** [comment] 2024-06-14 21:20
Same: 
![image](https://github.com/SoftFever/OrcaSlicer/assets/19464921/ef80901a-2359-475e-9ad6-1964d19249e0)
![image](https://github.com/SoftFever/OrcaSlicer/assets/19464921/77d55c99-f454-4623-b331-58e0f6d21c98)

**Comment by ExR90** [comment] 2024-06-22 08:21
I am having this exact problem. The linked fix in PR 5774, re: Filament shrink, for me is already at 100 so I am not sure that fix is related to this problem.

**Comment by igiannakas** [comment] 2024-06-22 08:51
Can you post your project file? It helps with trouble shooting as I cannot reproduce this issue right now.

**Comment by SuddenlyPineapple** [comment] 2024-07-01 06:25
It was fixed in https://github.com/SoftFever/OrcaSlicer/pull/5774 . Install version 2.1.1 ;) I think this issue might be closed :)

**Closed** 2024-07-01 15:18 UTC
Labels: bug
