### ISSUE TITLE
Dark Mode: Inconsistent GUI

### ISSUE THREAD

**Issue by foreachthing** [SoftFever/OrcaSlicer#2165] opened 2023-09-19 04:43 UTC
### OrcaSlicer Version

1.7

### OS version

Windows 10, 11

### Printer

Ultimaker 2

### How to reproduce

1. Change to Dark Mode first.
1. Open "Printer Settings"
1. Open "Set ..." in "Printable Area"
1. Observe: ![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/e109a1d8-d047-4907-85a8-49845f7558f6)

### Actual results

It's hard, for me, to make out whatever is in the Settings groupbox.

Almost the same dialogbox in "Normal" mode: 
![image](https://github.com/SoftFever/OrcaSlicer/assets/10420187/b1228638-5afd-4c76-9a86-91208a479e47)

Even here, the "Load ..." (I guess??) button is way too small

Another user (ShryuKt) took the same screenshots in issue 83 _(not linked on purpose!)_.

### Expected results

Consistent GUI.

### Project file & Debug log uploads

n/a

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by guestisp** [comment] 2023-09-19 12:43
probably duplicate of https://github.com/SoftFever/OrcaSlicer/issues/2086

**Closed** 2023-09-19 17:38 UTC
Labels: bug
