### ISSUE TITLE
Support top interface printing middle air

### ISSUE THREAD

**Issue by R4toLoko** [SoftFever/OrcaSlicer#2145] opened 2023-09-17 07:36 UTC
### OrcaSlicer Version

1.7.0

### OS version

Mint Cinnamon 21.1

### Printer

Voron Trident

### How to reproduce

1. Slice anything that requires support forced or not
2. Check the support top interface

### Actual results

I don't use supports so this could be me doing user stuff.
I am testing this Organic tree and the top interface is being printed middle air.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/ccdb300b-1cef-4f4d-bebf-e5926922901f)

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/4e1adca5-9531-4dfe-82f5-292cc745b572)

If I reduce the top interface spacing, it improves but still prints middle air.

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/10747c91-970a-4073-b519-186745698e6a)

### Expected results

Top interface layer should be printed like tree does:

![image](https://github.com/SoftFever/OrcaSlicer/assets/35049512/e7574ee6-541b-4234-8f31-be9690209858)

### Project file & Debug log uploads

[master_chief.zip](https://github.com/SoftFever/OrcaSlicer/files/12642282/master_chief.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

**Comment by igiannakas** [comment] 2023-09-18 10:05
duplicate of this: https://github.com/SoftFever/OrcaSlicer/issues/2038

Same as prusa slicer - bug is carried over: https://github.com/prusa3d/PrusaSlicer/issues/11155

**Comment by R4toLoko** [comment] 2023-09-18 14:33
> duplicate of this: https://github.com/SoftFever/OrcaSlicer/issues/2038
> 
> Same as prusa slicer - bug is carried over: https://github.com/prusa3d/PrusaSlicer/issues/11155
> 
> 

I need to start searching first more before opening a ticket 🤦

**Closed** 2023-09-18 14:33 UTC
Labels: bug
