### ISSUE TITLE
libwebkit2gtk error prevents using the software even after installing libwebkit2gtk-4.1-0 

### ISSUE THREAD

**Issue by MFernflower** [SoftFever/OrcaSlicer#5430] opened 2024-05-22 22:29 UTC
### OrcaSlicer Version

2.0.0 AppImage build and the latest nightly build does this as well (OrcaSlicer_Linux_V2.1.0-dev.AppImage)

### Operating System (OS)

Linux

### OS Version

Xubuntu 24.04 LTS Noble Numbat

### Additional system information

core i5 system with 32 gb of ram running Xubuntu 24.04 LTS 

### Printer

CREALITY K1

### BUG

Appimage fails to launch with error:

/tmp/.mount_OrcaSlsTuRmG/bin/orca-slicer: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

issue still occurs even after I have installed libwebkit2gtk-4.1-0

**Comment by buzzhuzz** [comment] 2024-05-23 09:16
Duplicate of #4616 

Attempt to fix it made in #5203, but there are issue found during code review which I don't actually know how to fix yet.

**Comment by Luke56784** [comment] 2024-05-23 13:45
You have to install 4.0. Not 4.1
But it's not in the repository's anymore with 24.04.

You also can link it by executing 

`sudo ln -sf /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so.0 /usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.0.so.37
sudo ln -sf /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.1.so.0 /usr/lib/x86_64-linux-gnu/libjavascriptcoregtk-4.0.so.18`


 https://github.com/bambulab/BambuStudio/issues/3973

**Comment by MFernflower** [comment] 2024-05-23 17:22
I will try this when I get back home


Thank you

**Comment by GA3Dtech** [comment] 2024-05-25 08:03
I had same issue on Ubutu LTS 24.04 fresh install

I can confirm that linking path is working

thk

**Comment by mikeperalta1** [comment] 2024-05-27 22:33
+1 issue began immediately after upgrading to Ubuntu 24.04

**Comment by ffries** [comment] 2024-06-20 08:09
All these issue are related :
https://github.com/SoftFever/OrcaSlicer/issues?q=libwebkit2gtk-4.0.so.37

**Comment by MFernflower** [comment] 2024-06-20 16:43
@ffries the two bash commands given by Luke fix the issue

**Closed** 2024-07-03 17:27 UTC
Labels: bug
