### ISSUE TITLE
1.9: GUI issue on Windows when display scaling is > 100%

### ISSUE THREAD

**Issue by Noisyfox** [SoftFever/OrcaSlicer#3000] opened 2023-12-05 06:52 UTC
### OrcaSlicer Version

1.9

### OS version

Windows 11

### Printer

N/A

### How to reproduce

1. Set display scaling to say 200%
2. Open the 1.9 dev build

### Actual results

1. Icon & text size issue: (left 1.8.1, right 1.9 dev)
![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/eb09f087-2003-4d35-b854-dd1f29b52b2a)
The icons are too large, while the title text is too small.

2. Right mouse menu y position is off. When you right click on the plate, the context menu is no longer positioned at the mouse cursor, but shifted up.

### Expected results

It should look the same as 1.8.

### Project file & Debug log uploads

N/A

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by Noisyfox** [comment] 2023-12-05 06:53
(At least) part of the issue was caused by not using the bitmapbundle, as now the size of the toolbar icons are correct after https://github.com/Noisyfox/OrcaSlicer/commit/0a0376a76d1d6b781e50e5a30d546df7dd241094 :

![image](https://github.com/SoftFever/OrcaSlicer/assets/1537155/906f8f88-0176-4ccb-be81-5a832a7923b8)

**Comment by Noisyfox** [comment] 2023-12-05 07:21
Also, I believe 
https://github.com/SoftFever/OrcaSlicer/blob/main/src/slic3r/GUI/wxExtensions.cpp#L892-L894
might be caused by the line here
https://github.com/SoftFever/OrcaSlicer/blob/25a055491ee8ef664497d480e1d0e06a71bbea59/src/slic3r/GUI/Widgets/SwitchButton.cpp#L141

**Comment by Ocraftyone** [comment] 2023-12-06 06:45
You are at the same position that I am. I just forgot to respond to the comment. There also seems to be an issue with the text size in the top bar not scaling correctly, but I do not see any code responsible for that. I am still looking. 

As for the switch button, I don't believe that should be causing the issue for the Global/Objects switcher. It is most likely the cause for the advanced toggle though. I think that to fix the advanced toggle I just need to re-implement the scale to size function that BBL implemented for regular bitmaps

**Comment by Ocraftyone** [comment] 2023-12-06 08:49
Got text scaling fixed. Not sure what changed that prevents it from not being done automatically, but oh well 🤷.

**Comment by Ocraftyone** [comment] 2023-12-06 09:11
yes. I noticed that too during development. Though I fixed it but it must have been reapplied when I went back through the patches

**Comment by Ocraftyone** [comment] 2023-12-06 15:25
@Noisyfox I think that I figured out the scaling issue. For some reason, when PS updated their code to use the new versions of wx, they rewrote how they get the svg data. Instead of parsing the SVG data and using the resulting image to help scale the image based on the target px, it just reads the raw svg file and passes that to wx to parse and load. In wx's implementation, you are required to give an exact dimension and we were passing the px value for both width and height. This is what was giving the funky images when the input was not exactly square. This should be pretty easy to remedy by switching back to the nsvg function that parses the read data into an nsvg image, get the scaled dimensions of the svg, then pass to wx to create the bitmap bundle. I am working on an implementation rn.

**Comment by tsmith35** [comment] 2023-12-20 00:33
Is there a fix I can make to current source to regain the normal sizing from before? I have to run compatibility mode to get the normal layout, but that comes with some quirky behavior and fuzzy graphics. Any help is appreciated. The new features look very nice.

**Comment by Noisyfox** [comment] 2023-12-20 00:57
> Is there a fix I can make to current source to regain the normal sizing from before? I have to run compatibility mode to get the normal layout, but that comes with some quirky behavior and fuzzy graphics. Any help is appreciated. The new features look very nice.

Try this PR build https://github.com/SoftFever/OrcaSlicer/pull/3032

**Comment by Ocraftyone** [comment] 2023-12-20 00:57
I just merged main into the PR tied to this issue. This will allow you to run 1.9dev with the current patches. You can get an artifact [here](https://github.com/SoftFever/OrcaSlicer/actions/runs/7269481813) when it finishes building.

**Comment by tsmith35** [comment] 2023-12-20 02:15
Okay, seems to look great and work great. The only remaining strangeness is on the calibration tab. Screenshots attached. Windows 10 22H2 with compatibility features disabled for OrcaSlicer. Resolution is 3840x2160 with 175% scaling.
![Main Screen](https://github.com/SoftFever/OrcaSlicer/assets/7685333/261c9465-1aff-45dd-bd7b-5185b5c35c16)
![About](https://github.com/SoftFever/OrcaSlicer/assets/7685333/8b52af30-b143-4acf-83a5-da3dc822d515)
![Calibration](https://github.com/SoftFever/OrcaSlicer/assets/7685333/0a10ea45-1dd2-4e21-8243-3aada78aa3f0)

**Comment by tsmith35** [comment] 2023-12-20 02:17
Oops, forgot this one...
![Calibration 2](https://github.com/SoftFever/OrcaSlicer/assets/7685333/4e1c4a09-f9b5-44a9-823a-bc5e8a57c603)

**Closed** 2023-12-21 08:27 UTC
Labels: bug, 1.9
