### ISSUE TITLE
FR: fuzzy top skin....Awesome!

### ISSUE THREAD

**Issue by PhilBaz** [SoftFever/OrcaSlicer#7209] opened 2024-10-23 16:01 UTC
### Is there an existing issue for this feature request?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

https://www.youtube.com/watch?v=EhKnqHey6l8

Fuzzy top skin. Obviously this is amazing.

### Which printers will be beneficial to this feature?

All

### Describe the solution you'd like

Fuzzy top skin.

**Comment by vgdh** [comment] 2024-10-23 16:29
duplicate of https://github.com/SoftFever/OrcaSlicer/issues/7152

**Comment by PhilBaz** [comment] 2024-10-23 16:31
whoops.

**Closed** 2024-10-23 16:31 UTC
Labels: enhancement
