### ISSUE TITLE
Scale flow rate chits (X & Y) on small build plates

### ISSUE THREAD

**Issue by jamincollins** [SoftFever/OrcaSlicer#2347] opened 2023-10-07 01:17 UTC
**Is your feature request related to a problem? Please describe.**

I'm going through filament calibration on a Voron v0.  I'm at the flow rate.  However, due to the size of the chits created they won't all fit on the print bed.  AFAICT, a simple solution is scaling X & Y down to ~80% of the original size.  I'm guessing this won't impact the calibration (if it will please advise). 

**Which printers will be beneficial to this feature**
Any printer with a smaller build plate than the generated chits.

**Describe the solution you'd like**
See above.

**Comment by Ocraftyone** [comment] 2023-10-07 03:01
Duplicate of #2256

**Comment by ichibana** [comment] 2024-01-04 05:48
@jamincollins i'm in the same boat. did you scale and calibrate without issues?

**Comment by jamincollins** [comment] 2024-01-04 15:53
Yes, just don't touch the z axis

**Comment by ichibana** [comment] 2024-01-04 17:24
Thanks!

**Comment by ChaosBlades** [comment] 2024-03-11 22:55
Visual representation of issue. It is super close to fitting. Should be a relatively easy no compromises fix. I propose making them taller and narrower. Could also close spacing to 1mm.
![Screenshot from 2024-03-11 18-46-11](https://github.com/SoftFever/OrcaSlicer/assets/7530545/07120268-73fb-42a0-9f90-4322be8258ed)

**Comment by jamincollins** [comment] 2024-03-11 22:56
The second set is worse since it has ten tiles.

**Comment by ChaosBlades** [comment] 2024-03-11 23:04
> The second set is worse since it has ten tiles.

Forgot about that.
![Screenshot from 2024-03-11 19-01-16](https://github.com/SoftFever/OrcaSlicer/assets/7530545/fb44dd9e-d1dc-476b-9f27-7476494501d6)

 Narrower and shave off some of the space above and below the numbers. Even at 80% scale still plenty of space could be saved.
 ![Screenshot from 2024-03-11 19-02-27](https://github.com/SoftFever/OrcaSlicer/assets/7530545/f5d72bfe-1d19-465b-906f-6d62ffe15111)

**Comment by Ocraftyone** [comment] 2024-03-11 23:16
I have a model that is similar to the super slicer version. I will try and implement that this week as an option.

**Closed** 2024-05-18 04:50 UTC
