### ISSUE TITLE
Text and background have same color.

### ISSUE THREAD

**Issue by GAZ082** [SoftFever/OrcaSlicer#2289] opened 2023-10-01 22:48 UTC
### OrcaSlicer Version

1.7.0

### OS version

Linux - Gnome 44.5 Wayland

### Printer

X

### How to reproduce

Go to object settings:

![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/b559b2df-2572-472e-ae50-b712d0dd7a98)

### Actual results

Foreground and background have the same color.

### Expected results

Foreground white, background dark, as happens in the global menu:

![image](https://github.com/SoftFever/OrcaSlicer/assets/100194/4c7fc696-3ffa-4b6b-b5ef-076f4939d21e)

### Project file & Debug log uploads

X

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by daduke** [comment] 2023-10-02 10:53
same here, Fedora 38 wayland

**Comment by TexZeTech** [comment] 2023-10-03 17:50
Raised here https://github.com/SoftFever/OrcaSlicer/issues/2086

**Comment by discip** [comment] 2023-10-04 10:46
@GAZ082
Please consider closing this since it is a duplicate of #2086 as already mentioned by @TexZeTech. 😊

**Closed** 2023-10-04 12:37 UTC
Labels: bug
