### ISSUE TITLE
THUMBNAIL_BLOCK

### ISSUE THREAD

**Issue by za-x-az** [SoftFever/OrcaSlicer#2253] opened 2023-09-28 17:26 UTC
**Which printers will be beneficial to this feature**
all klipper printers

**Describe the solution you'd like**
When thew need for manual gcode edit arives the THUMBNAIL_BLOCK is rather badly located at the start.

**Describe alternatives you've considered**
Move the THUMBNAIL_BLOCK to the end of the file like cura.

**Additional context**

**Comment by discip** [comment] 2023-09-29 05:22
@za-x-az
Seems to be a duplicate of #2200.
If so, please consider closing this one. 😊

**Comment by za-x-az** [comment] 2023-09-29 18:15
> @za-x-az Seems to be a duplicate of #2200. If so, please consider closing this one. 😊

You might be right, i did go a good searvh but i looked for the use of Thumbnail 😁 and well found nothing 🤷‍♂️

**Closed** 2023-09-29 18:15 UTC
