### ISSUE TITLE
OrcaSlicer vs Superslicer printing speed and filament consumption

### ISSUE THREAD

**Issue by reapola** [SoftFever/OrcaSlicer#740] opened 2023-04-12 11:36 UTC
**Describe the bug**
Wishing to move from Superslicer to OrcaSlicer and have copied my settings across but I'm seeing a difference in benchy printing time of 18mins along with ~25cm of filament used.  Any suggestions on what could be causing this?

**To Reproduce**
Take a Superslicer profile and replicate in OrcaSlicer using classic perimeters.

**Expected behavior**
Printing time and filament used should be similar.

More detail....

**Estimated time to complete**
![image](https://user-images.githubusercontent.com/36609013/231442053-d56a41dc-fefc-48ed-999c-5dcad7413f82.png)

**Printed time difference to confirm**
![image2](https://user-images.githubusercontent.com/36609013/231442258-3e13d85b-c09b-4cab-9fbb-ea06a40d1aeb.png)

If I set small perimeters threshold to 0mm instead of max of 20mm set in SS then I can get the time down to a difference of 7mins

**Orca Setting**
![image3](https://user-images.githubusercontent.com/36609013/231442351-d8dd2bb7-b584-40ad-b311-7663d26c4169.png)

**SS setting**
![image4](https://user-images.githubusercontent.com/36609013/231442409-c0a5a901-e166-4cc0-a0a6-00d06486f0f1.png)

**Speed comparison with small perimeters set to 0 on orca.**
![orca_ss_speed](https://user-images.githubusercontent.com/36609013/231441076-c9e0847c-c9ca-4d37-a9f8-23997ce210ff.jpg)

**Time comparison with small perimeters set to 0 on orca.**
![orca_ss_time](https://user-images.githubusercontent.com/36609013/231441141-3f285a3b-74d8-4a36-8920-9ac18a5b6aa2.jpg)

**Printer model**
Voron 2.4 300

**Desktop (please complete the following information):**
 - OS: Windows 11 with Orca 1.6.1

**Comment by reapola** [comment] 2023-04-12 11:40
**Superslicer settings (rename to .ini)**
[SuperSlicer_config_bundle.txt](https://github.com/SoftFever/OrcaSlicer/files/11210916/SuperSlicer_config_bundle.txt)

**Orca Settings (rename to .json)**
[Metis Voron 2.4 300 0.4 nozzle.txt](https://github.com/SoftFever/OrcaSlicer/files/11210930/Metis.Voron.2.4.300.0.4.nozzle.txt)
[Voron eSUN ABS.txt](https://github.com/SoftFever/OrcaSlicer/files/11210931/Voron.eSUN.ABS.txt)
[Metis 0.20mm Standard @Voron.txt](https://github.com/SoftFever/OrcaSlicer/files/11210932/Metis.0.20mm.Standard.%40Voron.txt)

**Comment by H4kunaM4tata** [comment] 2023-04-15 14:26
I don't think you will have them both printing exactly with the same time.

Trident here with `klipper_estimator`, in many cases OrcaSlicer is actually faster than PrusaSlicer, in others I've found that OrcaSlicer was taking longer because the profiles weren't exactly the same.

**Comment by SoftFever** [comment] 2023-04-18 14:36
Thanks. 
Closing this ticket as this is not a bug.

**Closed by SoftFever** 2023-04-18 14:36 UTC
Labels: bug
