### ISSUE TITLE
missing public overhang documentation

### ISSUE THREAD

**Issue by TheTesla** [SoftFever/OrcaSlicer#4050] opened 2024-02-11 21:14 UTC
### OrcaSlicer Version

1.9.0

### OS version

Ubuntu 23.10

### Printer

Creality K1

### How to reproduce

1. Go to _Overhang speed_ in _Speed_ section
2. Tooltip show URL which is not public - https://github.com/SoftFever/OrcaSlicer/wiki/slow-down-for-overhang

### Actual results

```
You do not have permission to update this wiki.
```

### Expected results

Show the wiki entry about overhang, which describes _Classic mode_ and _Slow down for curled perimeters_

### Project file & Debug log uploads

https://github.com/SoftFever/OrcaSlicer/wiki/slow-down-for-overhang

### Checklist of files to include

- [ ] Log file
- [ ] Project file

**Comment by gshpychka** [comment] 2024-03-15 20:25
Duplicate of https://github.com/SoftFever/OrcaSlicer/issues/2724

**Closed** 2024-06-05 13:59 UTC
Labels: bug
