### ISSUE TITLE
Arc fitting does not work correctly

### ISSUE THREAD

**Issue by majkne** [SoftFever/OrcaSlicer#1329] opened 2023-06-12 07:56 UTC
Compared to bambu slicer arc fitting does not work properly

Bambu
![image](https://github.com/SoftFever/OrcaSlicer/assets/80316636/5817e3ba-7904-422d-ab8f-ad83505348a0)
Orca
![image](https://github.com/SoftFever/OrcaSlicer/assets/80316636/597f5bef-f6e5-4044-91eb-8fac8ed1ad36)

Both tested on the same parameters with a classic generator

You can see that the length of the g code for layer is different, for bambu it is around 40 and for orca it is 370 commands

Bambu Studio 1.6.2.4
Orca slicer 1.6.3

**Comment by psiberfunk** [comment] 2023-06-12 19:57
dupe of #1257 , which has a better replication case attached.  Suggest to close this one.

**Comment by bani6809** [comment] 2023-06-22 07:10
please close this as dupe of #1257

**Closed** 2023-06-22 07:33 UTC
Labels: bug
