### ISSUE TITLE
A G-code path goes beyond the max print height

### ISSUE THREAD

**Issue by CadDaddy42** [SoftFever/OrcaSlicer#4754] opened 2024-03-28 18:23 UTC
### Is there an existing issue for this problem?

- [X] I have searched the existing issues

### OrcaSlicer Version

2.0.0 Beta

### Operating System (OS)

Windows

### OS Version

Windows 11

### Printer

Bambu Lab P1S

### How to reproduce

Specific model worked fine in 1.9.0. P1S, 0.6mm nozzle, 0.62 line width, 0.24 layer height, scarf joint and conditional checkboxes are checked, no other new features from the beta have been messed with beyond whatever is automatically different with my custom profile. Adaptive layer height not enabled. 

### Actual results

I get an error stating 'A G-code path goes beyond the max print height'. In 'prepare' screen size reports correctly as 60.46mm tall. After slicing, I get the error message and look over at the layer slider in the preview window and it;s reporting the top layer as 925440 mm - scroll down 1 layer with the arrow key, and it's at layer 251 at 60.30mm. Change the layer height to 0.16 and it slices as expected. 

### Expected results

I should be able to slice at any reasonable layer height and not get 1 km layer height for the top layer... 

### Project file & Debug log uploads

[Crocodile_Head_Bug.zip](https://github.com/SoftFever/OrcaSlicer/files/14791735/Crocodile_Head_Bug.zip)
[log.zip](https://github.com/SoftFever/OrcaSlicer/files/14791850/log.zip)

### Checklist of files to include

- [ ] Log file
- [X] Project file

### Anything else?

![Screenshot 2024-03-28 102443](https://github.com/SoftFever/OrcaSlicer/assets/146412560/b5f1e46f-c72c-4d1a-beda-41ba6c723d03)

**Comment by SoftFever** [comment] 2024-03-30 05:57
confirmed.
This happens when scarf joint is used.
Looks like a bug for the gcode preview for scarf joint.
@Noisyfox any thoughts?

**Comment by Edzi11** [comment] 2024-03-31 20:31
Glad SoftFever got a chance to look at this. I posted the same issue a while back but got no responses on it. Sounds like maybe a graphical bug? I went ahead and sent the file to the printer to see if anything happens on the very last layer.

**Comment by Coare1** [comment] 2024-03-31 22:33
Same issue here with a different model. For me I'm on 2.0.0 full release, and when I turn on Arachne walls, precise wall, and scarf joint the issue occurs. It also only seems to happen on CoreXY machines? It doesn't happen when slicing for an Ender 3 V2 or Prusa MK3S, but does occur for a Qidi X-Smart 3 and Bambu Lab P1S.
Here's the 3MF: [cone_bug.zip](https://github.com/SoftFever/OrcaSlicer/files/14817830/cone_bug.zip)

**Comment by lee-kev** [comment] 2024-04-02 01:22
I get the same trying to print something I've printed many times.

K1Max
2.0.0 Full
- Arachne walls
-  Scarf joint (Contour)

I disable Scarf joint and it slices ok.

**Comment by Noisyfox** [comment] 2024-04-02 12:56
Will take a look soon.

**Comment by Noisyfox** [comment] 2024-04-02 13:26
OK I've found the issue. As a temporary workaround, you could turn off arc fitting. This issue will be fixed in the next release.

**Closed** 2024-04-11 14:12 UTC
Labels: bug

**Comment by januar3829** [comment] 2024-07-06 03:09
I'm still getting this exakt error

**Comment by Cilsor** [comment] 2024-08-01 16:50
I have this same issue, and it only occurs when I am trying to do both adaptive layer height and use experimental scarf joints. The two conflict with the same error code as mentioned above most often when I have a adaptive layer height with a quality level number lower than .5

Playing with steps, and scarf length, sometimes allows a model to slice properly, or when that fails, pushing the adaptive layer height quality >0.5 will do the trick. This is regardless of classic or arachne walls being enabled. 

I think the two algorithms are conflicting in some way.

**Comment by Noisyfox** [comment] 2024-08-02 00:53
> I have this same issue, and it only occurs when I am trying to do both adaptive layer height and use experimental scarf joints. The two conflict with the same error code as mentioned above most often when I have a adaptive layer height with a quality level number lower than .5
> 
> Playing with steps, and scarf length, sometimes allows a model to slice properly, or when that fails, pushing the adaptive layer height quality >0.5 will do the trick. This is regardless of classic or arachne walls being enabled.
> 
> I think the two algorithms are conflicting in some way. A rounding error perhaps?

Could you provide a 3mf file that can reproduce this issue?

**Comment by Cilsor** [comment] 2024-08-02 01:45
I cannot, it's a licensed file. That said, it was definitely something to do with both adaptive layer height and scarf turned on. Eventually, trying to re-slice it and play with layer thicknesses and smoothing / changing amount of adaptiveness, the whole program crashed.  Re-launching and retrying still presented the error. 

Now that I am trying to recreate the issue today with the same settings, I can't. I power off my machine entirely every night, so I'm wondering if some kind of error was occurring where something was staying in ram that shouldn't have? or in some sort of cache? 

The only thing I lost between yesterday and today with this error was custom painted layer seams, using both blue and red, respectively, to ward around eye sockets. The doll was meant to have resin/acrylic eyes put behind the opening, so too, it could have been some interplay making it impossible for the scarf to find someplace with enough steps/length to do what was demanded of it in the context of also having adaptive layer height. 

With my redrawn layer seams, this time, maybe it found more appropriate places to start and stop my loops. 

If I manage to cause it again I'll report back with a project file and my print settings saved to the project.

**Comment by marcastle18** [comment] 2025-03-25 23:16
AFINAL DA PRA IMPRIMIR OU NÃO, COM ESTE ERRO?
